if(QPPJS_ENABLE_COVERAGE AND QPPJS_ENABLE_ASAN)
    message(FATAL_ERROR "QPPJS_ENABLE_COVERAGE and QPPJS_ENABLE_ASAN cannot both be ON")
endif()

function(qppjs_set_build_metadata name value)
    set(${name} "${value}" CACHE INTERNAL "QppJS build metadata")
endfunction()

function(qppjs_setup_project_configuration)
    set(QPPJS_GLOBAL_COMPILER_OPTIONS)
    set(QPPJS_GLOBAL_LINK_OPTIONS)

    if(WIN32)
        qppjs_set_build_metadata(QPPJS_PLATFORM windows)
    elseif(APPLE)
        qppjs_set_build_metadata(QPPJS_PLATFORM macos)
    else()
        qppjs_set_build_metadata(QPPJS_PLATFORM linux)
    endif()

    get_property(is_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(is_multi_config)
        qppjs_set_build_metadata(QPPJS_IS_MULTI_CONFIG true)
    else()
        qppjs_set_build_metadata(QPPJS_IS_MULTI_CONFIG false)
    endif()
    qppjs_set_build_metadata(QPPJS_GENERATOR_NAME "${CMAKE_GENERATOR}")

    if(MSVC)
        qppjs_set_build_metadata(QPPJS_COMPILER_FAMILY msvc)
        qppjs_set_build_metadata(QPPJS_COVERAGE_BACKEND unsupported)

        set(QPPJS_GLOBAL_COMPILER_OPTIONS /W4 /utf-8 /WX)
    else()
        if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            qppjs_set_build_metadata(QPPJS_COMPILER_FAMILY gcc)
            qppjs_set_build_metadata(QPPJS_COVERAGE_BACKEND gcov)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
            qppjs_set_build_metadata(QPPJS_COMPILER_FAMILY appleclang)
            qppjs_set_build_metadata(QPPJS_COVERAGE_BACKEND llvm-cov)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            qppjs_set_build_metadata(QPPJS_COMPILER_FAMILY clang)
            qppjs_set_build_metadata(QPPJS_COVERAGE_BACKEND llvm-cov)
        else()
            qppjs_set_build_metadata(QPPJS_COMPILER_FAMILY "${CMAKE_CXX_COMPILER_ID}")
            qppjs_set_build_metadata(QPPJS_COVERAGE_BACKEND unsupported)
        endif()

        set(QPPJS_GLOBAL_COMPILER_OPTIONS -Wall -Wextra -Wpedantic -Wno-unused-parameter -Werror)

        if(QPPJS_ENABLE_ASAN)
            list(APPEND QPPJS_GLOBAL_COMPILER_OPTIONS -fsanitize=address -fno-omit-frame-pointer)
            list(APPEND QPPJS_GLOBAL_LINK_OPTIONS -fsanitize=address)
        endif()
        if(QPPJS_ENABLE_UBSAN)
            list(APPEND QPPJS_GLOBAL_COMPILER_OPTIONS -fsanitize=undefined)
            list(APPEND QPPJS_GLOBAL_LINK_OPTIONS -fsanitize=undefined)
        endif()
        if(QPPJS_ENABLE_COVERAGE)
            if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                list(APPEND QPPJS_GLOBAL_COMPILER_OPTIONS --coverage -O0 -g)
                list(APPEND QPPJS_GLOBAL_LINK_OPTIONS --coverage)
            elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
                list(APPEND QPPJS_GLOBAL_COMPILER_OPTIONS -fprofile-instr-generate -fcoverage-mapping -O0 -g)
                list(APPEND QPPJS_GLOBAL_LINK_OPTIONS -fprofile-instr-generate -fcoverage-mapping)
            else()
                message(FATAL_ERROR "QPPJS_ENABLE_COVERAGE is unsupported for compiler ${CMAKE_CXX_COMPILER_ID}")
            endif()
        endif()
    endif()

    set(QPPJS_GLOBAL_COMPILER_OPTIONS "${QPPJS_GLOBAL_COMPILER_OPTIONS}" PARENT_SCOPE)
    set(QPPJS_GLOBAL_LINK_OPTIONS "${QPPJS_GLOBAL_LINK_OPTIONS}" PARENT_SCOPE)
    
    add_compile_options(${QPPJS_GLOBAL_COMPILER_OPTIONS})
    add_link_options(${QPPJS_GLOBAL_LINK_OPTIONS})
endfunction()

function(qppjs_write_build_metadata)
    if(NOT DEFINED QPPJS_PLATFORM)
        return()
    endif()

    set(metadata_path "${CMAKE_BINARY_DIR}/qppjs-build-meta.json")
    set(test_binary "")
    if(TARGET qppjs_unit_tests)
        set(test_binary "$<TARGET_FILE:qppjs_unit_tests>")
    endif()

    file(GENERATE OUTPUT "${metadata_path}" CONTENT
        "{\n  \"platform\": \"${QPPJS_PLATFORM}\",\n  \"compiler_family\": \"${QPPJS_COMPILER_FAMILY}\",\n  \"generator\": \"${QPPJS_GENERATOR_NAME}\",\n  \"is_multi_config\": ${QPPJS_IS_MULTI_CONFIG},\n  \"coverage_enabled\": $<IF:$<BOOL:${QPPJS_ENABLE_COVERAGE}>,true,false>,\n  \"coverage_backend\": \"${QPPJS_COVERAGE_BACKEND}\",\n  \"test_binary\": \"${test_binary}\",\n  \"source_dir\": \"${PROJECT_SOURCE_DIR}\",\n  \"build_dir\": \"${CMAKE_BINARY_DIR}\"\n}\n")
endfunction()
